### ISSUE TITLE
Fix Intermittent ConcurrentModificationException

### ISSUE THREAD

**Issue by Tyler-Yates** [Tyler-Yates/Graphinator#38]
A ConcurrentModificationException is thrown intermittently at program start. The modification is on the button list.
```
Exception in thread "AWT-EventQueue-0" java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at visualization.Drawer.paintComponent(Drawer.java:164)
```

**Comment by Tyler-Yates** [comment]
Appears to be fixed by b922836e83fceb2ba89056e97bfefa6ee057d165
